name: Deploy

on:
  workflow_run:
    workflows: ["CI main"]
    types:
      - completed

jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.4.1"
      - uses: actions/checkout@v3
        with:
          clean: "true"
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
 